name: Build and push
on:
  push:
    branches:
      - master

jobs:
  work:
    name: Work
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2
      - name: Build & Push docker image
        uses: mr-smithers-excellent/docker-build-push@v4
        with:
          image: democraciaenred/somosmuchas-activa-back
          tag: latest
          registry: containers.pkg.github.com
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Trigger stack update
        uses: fjogeleit/http-request-action@master
        with:
          url: ${{ secrets.STACK_URL }}
          method: 'POST'
          customHeaders: '{"Accept":  "application/vnd.github.everest-preview+json"}'
          bearerToken: ${{ secrets.REGISTRY_PASSWORD }}
          data: '{"event_type": "update-stack"}'
