name: Build and push
on:
  push:
    branches:
      - master

jobs:
  work:
    name: Work
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2
      - name: Build & Push docker image
        uses: mr-smithers-excellent/docker-build-push@v4
        with:
          image: democraciaenred/somosmuchas-activa-back
          tag: latest
          registry: containers.pkg.github.com
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
